### ISSUE TITLE
Error compiling Arduino IDE for ESP8266

### ISSUE THREAD

**Issue by buitre-buitaker** [terrorsl/sMQTTBroker#1]
Hi,

Latest library version with latest Arduino IDE.

Compiling I get this error:

C:\Users\XXX\Documents\Arduino\libraries\sMQTTBroker\src/sMQTTClient.h:24:35: error: 'TCPClient' has not been declared
   24 |  sMQTTClient(sMQTTBroker *parent, TCPClient *client);
      |                                   ^~~~~~~~~
C:\Users\XXX\Documents\Arduino\libraries\sMQTTBroker\src/sMQTTClient.h:43:2: error: 'TCPClient' does not name a type; did you mean 'DNSClient'?
   43 |  TCPClient *_client;
      |  ^~~~~~~~~
      |  DNSClient

Thank you!

**Comment by terrorsl** [comment]
Ok, I check it
