### ISSUE TITLE
Send Message from Broker

### ISSUE THREAD

**Issue by conaito** [terrorsl/sMQTTBroker#10]
Is there a way to send a message from broker to the clients or a special client? if not can you implement such solution?
As far as i see there is not client as such in the library to can do it?

**Comment by terrorsl** [comment]
I'll see what i can do

**Comment by terrorsl** [comment]
i append function publish in broker, but not test it.

**Comment by conaito** [comment]
can you give me some sample code to how to use / test it?

**Comment by conaito** [comment]
nice! i will test it soon! thx a lot. Currently its ver ybad for me since the connect problem still exist and no other way is possible then reset the esp32. i need any fix if possible. yesterday i complete test over the day and the problem comes 100% after some time.. logs view nothing strange..looks like overload after some time of connect and disconnect and then no new client (on serial views 0 clients connected!) can connect to the broker - i must reset then :(

**Comment by terrorsl** [comment]
> nice! i will test it soon! thx a lot. btw. is this message set as retain?

now this message Qos 0 and not retain.

**Comment by henrythasler** [comment]
Works great, thanks! It's exactly what I was looking for.

**Comment by whiledpeterman** [comment]
Sort of continuing with this topic ....for/in the loop calling broker.update() is there a way to get notified or set up a call back function for when there is a valid subscribe to a new topic or a valid unsubscribe from a current topic? That way would know when and what to broadcast based only from the connected clients needs and desires. The envisioned use for this code would be to publish using broker->publish(topic,payload); shown above -With only the needed topics/payloads of connected client(s) out of the many many topic possibilities for our devices.

**Comment by terrorsl** [comment]
hi, there are no such functions now. But I can add, and it will be possible to receive events like the rest through the onEvent function

**Comment by whiledpeterman** [comment]
That would be excellent and appreciated!

**Comment by whiledpeterman** [comment]
Is there a way I am able to use the requested feature before the library is updated? Thanks

**Comment by terrorsl** [comment]
I plan to add a branch for development, all new functionality will go there, and then into the main and releases.
