### ISSUE TITLE
Message Receive

### ISSUE THREAD

**Issue by leftcake** [terrorsl/sMQTTBroker#14]
I am able to connect my client to the server, but I cant receive any message from the same topic. How to solve it?

**Comment by terrorsl** [comment]
Maybe you need subscribe to this topic

**Comment by leftcake** [comment]
You mean the broker? I see the simple example in the library, it does not use any other function except broker.init()

**Comment by terrorsl** [comment]
No, I mean on client. Subscribe to topic and then send message. Broker received message and send to all how subscribe
