### ISSUE TITLE
terminate client ??

### ISSUE THREAD

**Issue by DONGILBAE** [terrorsl/sMQTTBroker#20]
Hello...  I am new one. 
It is not a issues.. Just only want to know.
I want to terminate client when client has wrong id or password. 
how can i do? on broker

**Comment by terrorsl** [comment]
Hello, look advance example, function onEvent. New client send login and password, you check it and if it bad return false. Broker drop client automatically.

**Comment by DONGILBAE** [comment]
I see.. thanks a lot..

**Comment by terrorsl** [comment]
Client must have unique name. If one connect and other have same name it will drop
