### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by AlessioSavelli** [terrorsl/sMQTTBroker#27]
Hi, you do an amazing work. It is possible to modify the library to can receive my custom TCP Client and TCP Server? I would like to use Ethernet W5500 and ENC28J60 with ESP32.

Thanks you....

**Comment by terrorsl** [comment]
Hi, I don't quite understand what you want. if you are using something other than esp32, you can add support for your device. if you want to add a wired connection to esp32, then you don’t really need to modify anything, as far as I understand

**Comment by AlessioSavelli** [comment]
This is my Hardware configuration.
![ESP32-ETH](https://user-images.githubusercontent.com/91372363/200177782-c1551e5b-9d51-4375-ae06-a12bb3d3e72d.jpg)
![W5500 ETH](https://user-images.githubusercontent.com/91372363/200177783-71e121f8-dfde-4bf2-8b7c-c60a89ef7c33.jpg)

Is possible to modify  the library to accept my ethrnet socket ?

Ex.
Now with your library i need to initialize WiFi and after that i do this : 
    const unsigned short mqttPort=1883;
    broker.init(mqttPort);

I wolud like to initialize my ethernet and after that do like something this :
    const unsigned short mqttPort=1883;
    broker.init(mqttPort,EthTCPServer,EthTCPClient);

**Comment by terrorsl** [comment]
Your device like WT32_ETH01?

**Comment by AlessioSavelli** [comment]
nope
WT32_ETH01 use Chip LAN8720A , i use Chip W5500 or ENC28J60.... I have an idea of the change you should make to the library .... can I suggest it?

**Comment by terrorsl** [comment]
oh yes, I understand that there is a different chip, but I'm in terms of software connection. did you watch this topic #19? If the library to connect is the same, then you don't have to add anything. In any case, it is interesting to hear your suggestion for the code.

**Comment by AlessioSavelli** [comment]
i try to make a pull request. let's me knwo if you can see it

**Comment by AlessioSavelli** [comment]
done

**Comment by terrorsl** [comment]
Now you can add your client and server. Let me know if it helped or not.

**Comment by AlessioSavelli** [comment]
Yes, in part.
i created my file smqtt_user_socket.h and put this code insde:
#include <Ethernet.h>
class TCPClient: EthernetClient {
  public:
    bool isConnected() {
      if (Ethernet.linkStatus() == LinkON) return true;
      return false;
    }
};
class TCPServer: EthernetServer {
  public:
    void stop() {}
    bool isConnected() {
      if (Ethernet.linkStatus() == LinkON) return true;
      return false;
    }
};

but after i initialize the broker i get this error:
192.168.1.177
[   730][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=1883, ...)

assert failed: tcpip_send_msg_wait_sem IDF/components/lwip/lwip/src/api/tcpip.c:455 (Invalid mbox)


Backtrace:0x400834f9:0x3ffb25200x40087ff5:0x3ffb2540 0x4008cd6d:0x3ffb2560 0x400dedba:0x3ffb2690 0x400e93d5:0x3ffb26c0 0x400e9408:0x3ffb26e0 0x400dec31:0x3ffb2730 0x400d2266:0x3ffb2750 0x400d22dc:0x3ffb27a0 0x400d21e9:0x3ffb27c0 0x400d1ad3:0x3ffb27e0 0x400d45ee:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1344
load:0x40078000,len:13836
load:0x40080400,len:3608
entry 0x400805f0

I don't understand why it says this: : [   730][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=1883, ...)

can you help me?

**Comment by terrorsl** [comment]
Show how you init Ethernet

**Comment by terrorsl** [comment]
Insert define before include

**Comment by AlessioSavelli** [comment]
the problem remains.... 

Now to avoid conflicts I have modified the file 'sMQTTplatform.h' like this:
#if defined(SMQTT_USER_SOCKET)
// create and write your client and server
//#include "smqtt_user_socket.h"
#elif defined(WIN32)
ecc....


and my .ino like this :
#include <Ethernet.h>
#define SMQTT_USER_SOCKET
#include "smqtt_user_socket.h"
#include"sMQTTBroker.h"


#define ETH_SPI1_CS 5
byte mac[] = { 0xBE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
byte ip[] = { 192, 168, 1, 177 };
sMQTTBroker broker;
ecc.

**Comment by terrorsl** [comment]
Work? Write compiler log with conflict

**Comment by AlessioSavelli** [comment]
If i do not remove '#include "smqtt_user_socket.h"' from sMQTTplatform.h the compiler says :

C:\Users\AS\Documents\Arduino\libraries\sMQTTBroker\src/sMQTTplatform.h:8:10: fatal error: smqtt_user_socket.h: No such file or directory

then i remove #include "smqtt_user_socket.h" from sMQTTplatform.h and write 
:
----
#include <Ethernet.h>
#define SMQTT_USER_SOCKET
#include "smqtt_user_socket.h"
#include"sMQTTBroker.h"
....ecc
-----
in my .ino files
and the compiler works good but i still recive an error from esp32 in run time
----
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1344
load:0x40078000,len:13836
load:0x40080400,len:3608
entry 0x400805f0
192.168.1.177
[   728][V][WiFiServer.h:42] WiFiServer(): WiFiServer::WiFiServer(port=1883, ...)

assert failed: tcpip_send_msg_wait_sem IDF/components/lwip/lwip/src/api/tcpip.c:455 (Invalid mbox)


Backtrace:0x40083535:0x3ffb25200x40088089:0x3ffb2540 0x4008d185:0x3ffb2560 0x400e3316:0x3ffb2690 0x400ef81d:0x3ffb26c0 0x400ef87c:0x3ffb26e0 0x400e304d:0x3ffb2730 0x400d56ea:0x3ffb2750 0x400d5760:0x3ffb27a0 0x400d2705:0x3ffb27c0 0x400d1f33:0x3ffb27e0 0x400d7812:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...

**Comment by terrorsl** [comment]
change in sMQTTPlatform.h
```cpp
#if defined(SMQTT_USER_SOCKET)
// create and write your client and server
//#include"smqtt_user_socket.h"
#include<Arduino.h>
#include <Ethernet.h>
#define TCPClient EthernetClient
#define TCPServer EthernetServer
#define SMQTT_LOGD
#elif defined(WIN32)
```
Also check that this EthernetServer is working without a sMQTTBroker.

**Comment by terrorsl** [comment]
I checked the build on my esp in arduino id 2, unfortunately you can’t set SMQTT_USER_SOCKET globally, if you enable the build log in the settings, you can see that it will first compile the libraries and then the sketch. I suggest trying the following:
in sMQTTPlatform.h
```cpp
#define SMQTT_USER_SOCKET
#if defined(SMQTT_USER_SOCKET)
#include <Ethernet.h>

class _EthernetServer :public EthernetServer
{
public:
	_EthernetServer(uint16_t port):EthernetServer(port) {}
	virtual void begin() { EthernetServer::begin(); }
	virtual void begin(uint16_t port) { EthernetServer::begin(); }
	void end() {}
};
typedef _EthernetServer TCPServer;
typedef EthernetClient TCPClient;
#define SMQTT_LOGD
```
I have everything assembled and there were no errors when debugging. I hope this helps you.

**Comment by AlessioSavelli** [comment]
nothing is happening, i still have the same problem....
![image](https://user-images.githubusercontent.com/91372363/200927733-7483ae49-9837-4dc1-b3f3-8a455011a3d6.png)

**Comment by terrorsl** [comment]
Did you modify in smqttplatform.h ?

**Comment by AlessioSavelli** [comment]
yep

**Comment by terrorsl** [comment]
i will change the library so you can add your server but it will take some time

**Comment by terrorsl** [comment]
I'm also surprised that the code I wrote didn't work for you

**Comment by terrorsl** [comment]
```cpp
#include<sMQTTplatform.h>
#include<sMQTTBroker.h>

sMQTTBroker broker;
int main(int argc,char **argv)
{
	sMQTTOSServer *server = newsMQTTServer(1883);
	broker.init(server);

	int time = GetTickCount();
	for (;;)
	{
		broker.update();
		if (GetTickCount() - time > 1000)
		{
			broker.publish(std::string("test"), "test",0);
			time = GetTickCount();
		}
	}
	return 0;
}
```
For your own platform, you need to write your own class for the server and client, as an example, you can look at sMQTTWIN32.h or sMQTTESP32.h

**Comment by AlessioSavelli** [comment]
Can you make an example ?
