### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by conaito** [terrorsl/sMQTTBroker#3]
i try to compile it but get follow errors:
`In file included from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTBroker.h:5:0,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:1:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h: In constructor 'sMQTTClient::sMQTTClient(sMQTTBroker*, WiFiClient*)':
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h:44:15: error: 'sMQTTClient::_parent' will be initialized after [-Werror=reorder]
  sMQTTBroker *_parent;
               ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h:39:7: error:   'bool sMQTTClient::mqtt_connected' [-Werror=reorder]
  bool mqtt_connected;
       ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:3:1: error:   when initialized here [-Werror=reorder]
 sMQTTClient::sMQTTClient(sMQTTBroker *parent, TCPClient *client):_parent(parent), mqtt_connected(false)
Compiling .pio\build\m5stack-atom\FrameworkArduino\MD5Builder.cpp.o
 ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp: In member function 'void sMQTTClient::processMessage()':
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:192:19: warning: unused variable 'msg_id' [-Wunused-variable]
Compiling .pio\build\m5stack-atom\FrameworkArduino\Print.cpp.o
    unsigned short msg_id = (header[0] << 8) | header[1];
                   ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:236:19: warning: unused variable 'qos' [-Wunused-variable]
     unsigned char qos = *payload++;
                   ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:223:19: warning: unused variable 'msg_id' [-Wunused-variable]
    unsigned short msg_id = (header[0] << 8) | header[1];
                   ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'Unknown' not handled in switch [-Wswitch]
  switch (message.type())
         ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'ConnAck' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'PubAck' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'PubRec' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'PubComp' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'SubAck' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'UnSuback' not handled in switch [-Wswitch]
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:45:9: warning: enumeration value 'PingResp' not handled in switch [-Wswitch]
In file included from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h:4:0,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTBroker.h:5,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:1:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTMessage.h:67:32: warning: 'packeteIdent[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  void add(char byte) { incoming(byte); }
                                ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:139:9: note: 'packeteIdent[1]' was declared here
    char packeteIdent[2];
         ^
In file included from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h:4:0,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTBroker.h:5,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:1:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTMessage.h:67:32: warning: 'packeteIdent[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  void add(char byte) { incoming(byte); }
                                ^
.pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:139:9: note: 'packeteIdent[0]' was declared here
    char packeteIdent[2];
         ^
In file included from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTBroker.h:4:0,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:1:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTplatform.h: At global scope:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTplatform.h:34:20: warning: 'SMQTTTAG' defined but not used [-Wunused-variable]
 static const char *SMQTTTAG = "sMQTTBroker";
                    ^
In file included from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTClient.h:4:0,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTBroker.h:5,
                 from .pio\libdeps\m5stack-atom\sMQTTBroker\src\sMQTTClient.cpp:1:
.pio\libdeps\m5stack-atom\sMQTTBroker\src/sMQTTMessage.h:14:20: warning: 'debugMessageType' defined but not used [-Wunused-variable]
 static const char *debugMessageType[] = {
                    ^
cc1plus.exe: some warnings being treated as errors
*** [.pio\build\m5stack-atom\lib737\sMQTTBroker\sMQTTClient.cpp.o] Error 1`

**Comment by terrorsl** [comment]
As i undestand this from platformio. i wil try fix it.

**Comment by conaito** [comment]
this would be great
Am 28. Nov. 2021, 10:29 +0100 schrieb terrorsl ***@***.***>:
