### ISSUE TITLE
limiting retained topic

### ISSUE THREAD

**Issue by MUTTAQUI** [terrorsl/sMQTTBroker#30]
Hello, is it possible to limit the retained topic

**Comment by terrorsl** [comment]
Can you be more specific?

**Comment by MUTTAQUI** [comment]
More specifically, it would be great if I could specify the number of retained messages.  That way, it would save me a lot of esp32 ram.

**Comment by terrorsl** [comment]
The protocol does not provide an opportunity to restrict published messages. I can add functions to get the number of saved messages and let's say a list of topics. Further through standard mechanisms you can delete messages.

**Comment by MUTTAQUI** [comment]
First of all thanks for your reply, I would be grateful if you can provide API to get the total number of saved topics, and saved messages and delete the saved messages.

**Comment by MUTTAQUI** [comment]
> 

can you please give an example

**Comment by terrorsl** [comment]
```cpp
std::string name=broker.getRetaiedTopicName(index);
// remove topic
broker.publish(name,"");
```

**Comment by MUTTAQUI** [comment]
Thanks for your reply, this will save me a lot of heap memory.
