### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by navdeepssidhu** [terrorsl/sMQTTBroker#31]
I am using Arduino IDE and ESP8266. 
1. Previous version is compiling, but latest is producing the following error :
'UnSubscribe_sMQTTEventType' was not declared in this scope.

2. With previous version everything is working nicely only issue is the broker is able to receive short messages from cloud (though no such issue with local clients).   The below message is not received properly

"Timer1": {  "Enable": 0,  "Mode": 0,  "Time": "10:10",  "Window": 0,  "Days": "1000000", "Repeat": 1, "Output": 1, "Action": 0 }   

but if length is  reduced then no issue while  receiving   Timer1{"Enable":0,"Mode":0,"Time":"10:10"}

**Comment by terrorsl** [comment]
What Arduino IDE are you using?
Can you tell me more about messages from the cloud? Something is lost or does not come at all, and what is written in the broker when logging? Thanks

**Comment by navdeepssidhu** [comment]
I am using Arduino 1.8.19
It receives truncated message

**Comment by terrorsl** [comment]
Hello.
1. I don't have Arduino 1.8.19, I checked on Arduino 2, on version 0.1.7 there are no compilation errors.
Write a compilation log.
2. If a message comes from local clients in its entirety, then I think that we need to see if there are any restrictions on messages in the cloud.

**Comment by navdeepssidhu** [comment]
i have Installed Arduino 2.0.2 and updated all the libraries
while compiling advance example getting the following error:


C:\Users\ss\Documents\Arduino\libraries\sMQTTBroker\examples\advancebroker\advancebroker.ino: In member function 'virtual bool MyBroker::onEvent(sMQTTEvent*)':
C:\Users\ss\Documents\Arduino\libraries\sMQTTBroker\examples\advancebroker\advancebroker.ino:23:45: error: cannot convert 'sMQTTNewClientEvent*' to 'sMQTTSubUnSubClientEvent*' in initialization
   23 |                 sMQTTSubUnSubClientEvent *e=(sMQTTNewClientEvent*)event;
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             sMQTTNewClientEvent*

exit status 1

Compilation error: cannot convert 'sMQTTNewClientEvent*' to 'sMQTTSubUnSubClientEvent*' in initialization

**Comment by terrorsl** [comment]
Yes, you're right, it's a bug, I'll fix it. Thanks

**Comment by navdeepssidhu** [comment]
Thanks, example advancebroker.ino is compiling without errors, but if publish is added in the sketch      broker.publish("Topic" , "message" );       getting the following error in Arduino

c:/users/s/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: c:/users/s/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r'
c:/users/s/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld.exe: c:/users/s/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib\libc.a(lib_a-clock.o): in function `clock':
/workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by terrorsl** [comment]
hello, I compiled an example for esp8266 in arduino 2 and there were no linking errors

**Comment by navdeepssidhu** [comment]
Hi,
i have  updated Arduino to 2.0.3, download and reinstall the latest library, while compiling the following sketch and gotting the same error


#include<sMQTTBroker.h>

class MyBroker:public sMQTTBroker
{
public:
    bool onEvent(sMQTTEvent *event) override
    {
        switch(event->Type())
        {
        case NewClient_sMQTTEventType:
            {
                sMQTTNewClientEvent *e=(sMQTTNewClientEvent*)event;
                e->Login();
                e->Password();
            }
            break;
        case LostConnect_sMQTTEventType:
            WiFi.reconnect();
            break;
        case UnSubscribe_sMQTTEventType:
        case Subscribe_sMQTTEventType:
            {
                sMQTTSubUnSubClientEvent *e=(sMQTTSubUnSubClientEvent*)event;
            }
            break;
        }
        return true;
    }
};

MyBroker broker;
unsigned long Time;
unsigned long freeRam;

void setup()
{
    Serial.begin(115200);
    const char* ssid = "";         // The SSID (name) of the Wi-Fi network you want to connect to
    const char* password = ""; // The password of the Wi-Fi network
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
        delay(1000);
    }
    Serial.println("Connection established!");  
    Serial.print("IP address:\t");
    Serial.println(WiFi.localIP());
    
    const unsigned short mqttPort=1883;
    broker.init(mqttPort);
    // all done
    // your magic code
    Time=millis();
    freeRam=ESP.getFreeHeap();
};
void loop()
{
    broker.update();
    // your magic code
    if(millis()-Time>1000)
    {
      Time=millis();
      if(ESP.getFreeHeap()!=freeRam)
      {
        freeRam=ESP.getFreeHeap();
      Serial.print("RAM:");
      Serial.println(freeRam);
      broker.publish("Topic", "message");     // added publish here
      }
    }
};

**Comment by terrorsl** [comment]
```cpp
#include<sMQTTBroker.h>

class MyBroker:public sMQTTBroker
{
public:
bool onEvent(sMQTTEvent *event) override
{
switch(event->Type())
{
case NewClient_sMQTTEventType:
{
sMQTTNewClientEvent *e=(sMQTTNewClientEvent*)event;
e->Login();
e->Password();
}
break;
case LostConnect_sMQTTEventType:
WiFi.reconnect();
break;
case UnSubscribe_sMQTTEventType:
case Subscribe_sMQTTEventType:
{
sMQTTSubUnSubClientEvent *e=(sMQTTSubUnSubClientEvent*)event;
}
break;
}
return true;
}
};

MyBroker broker;
unsigned long Time;
unsigned long freeRam;

void setup()
{
Serial.begin(115200);
const char* ssid = ""; // The SSID (name) of the Wi-Fi network you want to connect to
const char* password = ""; // The password of the Wi-Fi network
WiFi.begin(ssid, password);
while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
delay(1000);
}
Serial.println("Connection established!");
Serial.print("IP address:\t");
Serial.println(WiFi.localIP());

const unsigned short mqttPort=1883;
broker.init(mqttPort);
// all done
// your magic code
Time=millis();
freeRam=ESP.getFreeHeap();

};
void loop()
{
broker.update();
// your magic code
if(millis()-Time>1000)
{
Time=millis();
if(ESP.getFreeHeap()!=freeRam)
{
freeRam=ESP.getFreeHeap();
Serial.print("RAM:");
Serial.println(freeRam);
broker.publish("Topic", "message"); // added publish here
}
}
};
```

**Comment by TeguhTeknisi** [comment]
I have this issue too, using esp8266 core 3.1.2
arduino ide 1.8.16 and 1.8.19
btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.

when compile the simplebroker, i dont have the error.
when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error.
but when i compile it on esp8266, i got this error


this the error log
/os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r'
/os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock':
/workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board LOLIN(WEMOS) D1 mini (clone).


Thanks.

**Comment by TeguhTeknisi** [comment]
i asked chatgpt, i got this answer

> That linker error comes from sMQTTBroker pulling in some libc function (clock() → _times_r) that isn’t implemented in the ESP8266 Arduino core. PicoMQTT is lightweight and header-only, so it doesn’t drag in those newlib dependencies, but sMQTTBroker does.

So, i can compile it, when change the example code like this

```
extern "C" {
  struct _reent;
  int _times_r(struct _reent *r, void *t) {
    return -1;   // not implemented on ESP8266
  }
}

#include<sMQTTBroker.h>

class MyBroker:public sMQTTBroker {
  public:
  bool onEvent(sMQTTEvent *event) override {
   switch(event->Type()) {
      case NewClient_sMQTTEventType: {
      sMQTTNewClientEvent *e=(sMQTTNewClientEvent*)event;
      e->Login();
      e->Password();
    }
    break;
    case LostConnect_sMQTTEventType:
    WiFi.reconnect();
    break;
    case UnSubscribe_sMQTTEventType:
    case Subscribe_sMQTTEventType: {
      sMQTTSubUnSubClientEvent *e=(sMQTTSubUnSubClientEvent*)event;
    }
    break;
   }
  return true;
  }
};

MyBroker broker;
unsigned long Time;
unsigned long freeRam;

void setup() {
  Serial.begin(115200);
  const char* ssid = "myssid"; // The SSID (name) of the Wi-Fi network you want to connect to
  const char* password = "mypass"; // The password of the Wi-Fi network
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
    delay(1000);
  }
  Serial.println("Connection established!");
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());

  const unsigned short mqttPort=1883;
  broker.init(mqttPort);
  // all done
  // your magic code
  Time=millis();
  freeRam=ESP.getFreeHeap();
};

void loop(){
  broker.update();
  // your magic code
  if(millis()-Time>1000){
   Time=millis();
   if(ESP.getFreeHeap()!=freeRam){
     freeRam=ESP.getFreeHeap();
     Serial.print("RAM:");
     Serial.println(freeRam);
     broker.publish("Topic", "message"); // added publish here
   }
  }
};
```

**Comment by terrorsl** [comment]
> I have this issue too, using esp8266 core 3.1.2 arduino ide 1.8.16 and 1.8.19 btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.
> 
> when compile the simplebroker, i dont have the error. when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error. but when i compile it on esp8266, i got this error
> 
> this the error log /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r' /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock': /workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r' collect2: error: ld returned 1 exit status exit status 1 Error compiling for board LOLIN(WEMOS) D1 mini (clone).
> 
> Thanks.

Hello, I checked on Arduino 1.8.19 library version 0.1.8 and version for ESP 8266 3.1.2 under Windows OS and everything compiles and links perfectly.

**Comment by terrorsl** [comment]
> i asked chatgpt, i got this answer
> 
> > That linker error comes from sMQTTBroker pulling in some libc function (clock() → _times_r) that isn’t implemented in the ESP8266 Arduino core. PicoMQTT is lightweight and header-only, so it doesn’t drag in those newlib dependencies, but sMQTTBroker does.
> 
> So, i can compile it, when change the example code like this
> 
> ```
> extern "C" {
>   struct _reent;
>   int _times_r(struct _reent *r, void *t) {
>     return -1;   // not implemented on ESP8266
>   }
> }
> 
> #include<sMQTTBroker.h>
> 
> class MyBroker:public sMQTTBroker {
>   public:
>   bool onEvent(sMQTTEvent *event) override {
>    switch(event->Type()) {
>       case NewClient_sMQTTEventType: {
>       sMQTTNewClientEvent *e=(sMQTTNewClientEvent*)event;
>       e->Login();
>       e->Password();
>     }
>     break;
>     case LostConnect_sMQTTEventType:
>     WiFi.reconnect();
>     break;
>     case UnSubscribe_sMQTTEventType:
>     case Subscribe_sMQTTEventType: {
>       sMQTTSubUnSubClientEvent *e=(sMQTTSubUnSubClientEvent*)event;
>     }
>     break;
>    }
>   return true;
>   }
> };
> 
> MyBroker broker;
> unsigned long Time;
> unsigned long freeRam;
> 
> void setup() {
>   Serial.begin(115200);
>   const char* ssid = "myssid"; // The SSID (name) of the Wi-Fi network you want to connect to
>   const char* password = "mypass"; // The password of the Wi-Fi network
>   WiFi.begin(ssid, password);
>   while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
>     delay(1000);
>   }
>   Serial.println("Connection established!");
>   Serial.print("IP address:\t");
>   Serial.println(WiFi.localIP());
> 
>   const unsigned short mqttPort=1883;
>   broker.init(mqttPort);
>   // all done
>   // your magic code
>   Time=millis();
>   freeRam=ESP.getFreeHeap();
> };
> 
> void loop(){
>   broker.update();
>   // your magic code
>   if(millis()-Time>1000){
>    Time=millis();
>    if(ESP.getFreeHeap()!=freeRam){
>      freeRam=ESP.getFreeHeap();
>      Serial.print("RAM:");
>      Serial.println(freeRam);
>      broker.publish("Topic", "message"); // added publish here
>    }
>   }
> };
> ```

clock() in smqttbroker used to create a unique ID when posting a message, if in your case uniqueness will not lead to an error you can use it.

**Comment by TeguhTeknisi** [comment]
> > I have this issue too, using esp8266 core 3.1.2 arduino ide 1.8.16 and 1.8.19 btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.
> > when compile the simplebroker, i dont have the error. when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error. but when i compile it on esp8266, i got this error
> > this the error log /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r' /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock': /workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r' collect2: error: ld returned 1 exit status exit status 1 Error compiling for board LOLIN(WEMOS) D1 mini (clone).
> > Thanks.
> 
> Hello, I checked on Arduino 1.8.19 library version 0.1.8 and version for ESP 8266 3.1.2 under Windows OS and everything compiles and links perfectly.

Thanks, i use library 0.1.8 from library manager too.
using lubuntu linux, but i got those error when using esp8266.

i will stick to using wemos esp32 s2 for now, its work, i change from PicoMQTT to sMQTTBroker to get Retain feature,
i will try on esp32 c3 super mini, for more cheaper chip.

best regrads,
teguh.

**Comment by terrorsl** [comment]
> > > I have this issue too, using esp8266 core 3.1.2 arduino ide 1.8.16 and 1.8.19 btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.
> > > when compile the simplebroker, i dont have the error. when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error. but when i compile it on esp8266, i got this error
> > > this the error log /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r' /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock': /workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r' collect2: error: ld returned 1 exit status exit status 1 Error compiling for board LOLIN(WEMOS) D1 mini (clone).
> > > Thanks.
> > 
> > 
> > Hello, I checked on Arduino 1.8.19 library version 0.1.8 and version for ESP 8266 3.1.2 under Windows OS and everything compiles and links perfectly.
> 
> Thanks, i use library 0.1.8 from library manager too. using lubuntu linux, but i got those error when using esp8266.
> 
> i will stick to using wemos esp32 s2 for now, its work, i change from PicoMQTT to sMQTTBroker to get Retain feature, i will try on esp32 c3 super mini, for more cheaper chip.
> 
> best regrads, teguh.

There may be problems with the library that includes the clock() function for Linux. In the smqttbroker library, you can replace clock() with millis(), perhaps this will be a solution for you.

**Comment by TeguhTeknisi** [comment]
> > > > I have this issue too, using esp8266 core 3.1.2 arduino ide 1.8.16 and 1.8.19 btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.
> > > > when compile the simplebroker, i dont have the error. when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error. but when i compile it on esp8266, i got this error
> > > > this the error log /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r' /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock': /workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r' collect2: error: ld returned 1 exit status exit status 1 Error compiling for board LOLIN(WEMOS) D1 mini (clone).
> > > > Thanks.
> > > 
> > > 
> > > Hello, I checked on Arduino 1.8.19 library version 0.1.8 and version for ESP 8266 3.1.2 under Windows OS and everything compiles and links perfectly.
> > 
> > 
> > Thanks, i use library 0.1.8 from library manager too. using lubuntu linux, but i got those error when using esp8266.
> > i will stick to using wemos esp32 s2 for now, its work, i change from PicoMQTT to sMQTTBroker to get Retain feature, i will try on esp32 c3 super mini, for more cheaper chip.
> > best regrads, teguh.
> 
> There may be problems with the library that includes the clock() function for Linux. In the smqttbroker library, you can replace clock() with millis(), perhaps this will be a solution for you.

Thanks, using
extern "C" {
  struct _reent;
  int _times_r(struct _reent *r, void *t) {
    return -1;   // not implemented on ESP8266
  }
}
and fixing something else in my other code
i can compile it, its running now.
using PicoMQTT i got free ram around 23KB ~ 26KB
using sMQTTBroker i got free ram around 12KB ~ 20KB

Thanks, i will see if it stable for few days so i can use it to change my esp32 s2

Edit
===
I change the clock() to millis() on sMQTTBroker.cpp, so i dont need to change my other code.
i hope its safe to run more than 49 days

**Comment by terrorsl** [comment]
> > > > > I have this issue too, using esp8266 core 3.1.2 arduino ide 1.8.16 and 1.8.19 btw, i dont use arduono ide 2.x because the ui and its heavy on my laptop.
> > > > > when compile the simplebroker, i dont have the error. when compile the advancebroker example on es32 S2 with arduino ide 1.8.18, i dont have the error. but when i compile it on esp8266, i got this error
> > > > > this the error log /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o):(.literal+0x4): undefined reference to `_times_r' /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: /os/lubuntu/bak/Arduino/1.8.16/portable/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/lib/libc.a(lib_a-clock.o): in function `clock': /workdir/repo/newlib/newlib/libc/time/clock.c:58: undefined reference to `_times_r' collect2: error: ld returned 1 exit status exit status 1 Error compiling for board LOLIN(WEMOS) D1 mini (clone).
> > > > > Thanks.
> > > > 
> > > > 
> > > > Hello, I checked on Arduino 1.8.19 library version 0.1.8 and version for ESP 8266 3.1.2 under Windows OS and everything compiles and links perfectly.
> > > 
> > > 
> > > Thanks, i use library 0.1.8 from library manager too. using lubuntu linux, but i got those error when using esp8266.
> > > i will stick to using wemos esp32 s2 for now, its work, i change from PicoMQTT to sMQTTBroker to get Retain feature, i will try on esp32 c3 super mini, for more cheaper chip.
> > > best regrads, teguh.
> > 
> > 
> > There may be problems with the library that includes the clock() function for Linux. In the smqttbroker library, you can replace clock() with millis(), perhaps this will be a solution for you.
> 
> Thanks, using extern "C" { struct _reent; int _times_r(struct _reent *r, void *t) { return -1; // not implemented on ESP8266 } } and fixing something else in my other code i can compile it, its running now. using PicoMQTT i got free ram around 23KB ~ 26KB using sMQTTBroker i got free ram around 12KB ~ 20KB
> 
> Thanks, i will see if it stable for few days so i can use it to change my esp32 s2
> # Edit
> 
> I change the clock() to millis() on sMQTTBroker.cpp, so i dont need to change my other code. i hope its safe to run more than 49 days

Yes, it safe
