### ISSUE TITLE
Use Param from example

### ISSUE THREAD

**Issue by conaito** [terrorsl/sMQTTBroker#8]
Can you give me a fix idea to use the payload and/or topic as example from "void onPublish(const std::string &topic, const std::string &payload)" ? i have no luck to get this string and serial print it

**Comment by terrorsl** [comment]
if the client has sent a message, the broker will send a message to this function before sending it out.

**Comment by conaito** [comment]
i know but i can't use payload as string in the code. can you give me a line of code to see how i use the message? As example to serial print it. This help me  lot

**Comment by conaito** [comment]
i mean Serial.printfn(payload); is not possible .. can you view me a correct usage ?

**Comment by terrorsl** [comment]
> i mean Serial.printfn(payload); is not possible .. can you view me a correct usage ?
``` c++
Serial.println(payload.c_str());
```

**Comment by terrorsl** [comment]
Now it is impossible, but I thought about it and will add it as a parameter a little later.

**Comment by conaito** [comment]
sounds great

**Comment by conaito** [comment]
as i see you added in latest update
