### ISSUE TITLE
Max Clients

### ISSUE THREAD

**Issue by conaito** [terrorsl/sMQTTBroker#9]
Are there set anywhere into the code a max clients variable? i made some tests with several clients connected up to MQTTool where i get then Status: Dsconnected MOSQ_CONN_LOST on try to connect

**Comment by terrorsl** [comment]
No, but if a client with the same ID is already connected, then the second one will be disconnected.

**Comment by conaito** [comment]
this was not the issue. i changed client id on the test

**Comment by conaito** [comment]
ì really played with just 2 clients yet.. connect, disconnect.. send messages etc. And after a while the problem with MOSQ_CONN_LOST is there.. there must be a small bug because same ID can´t be the issue (i really changed it)

**Comment by conaito** [comment]
thast really a problem because its simple a issue of time when the MQTT Broker can´t accept new connections and must be reset then.. bad. may you find a small fix for this scenario?

**Comment by terrorsl** [comment]
can you describe the problem more precisely so that I can reproduce it. I also connect from 2 clients and they connect without problems for me. Maybe the connection speed or some other factors?

**Comment by conaito** [comment]
Its not easy, simple to reproduce. I use MQTTool and MQTTX. Connect both, disconnect sometimes 1 and then the other.. send messages and repeat that all. Then after some time i see the connection problem if i try to reconnect with MQTTool. I try it all in local network and see not really any issues on debug output. May only here:
[D][sMQTTBroker.cpp:96] publish(): topic test Clients 1
[D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128

Err 128? is that a error?

**Comment by conaito** [comment]
what i see on serial is that 0 Client is connected so it can´t be the same id as you mentioned

**Comment by terrorsl** [comment]
> Its not easy, simple to reproduce. I use MQTTool and MQTTX. Connect both, disconnect sometimes 1 and then the other.. send messages and repeat that all. Then after some time i see the connection problem if i try to reconnect with MQTTool. I try it all in local network and see not really any issues on debug output. May only here: [D][sMQTTBroker.cpp:96] publish(): topic test Clients 1 [D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
> 
> Err 128? is that a error?

https://esp32.com/viewtopic.php?t=7610
https://github.com/espressif/arduino-esp32/issues/1921

Some people say that it help
```
void setup()
{
...
WiFi.begin(ssid, password);
WiFi.setSleep(false);// this code solves my problem
...
}
```

**Comment by conaito** [comment]
i tested it. it does not fix the problem

**Comment by terrorsl** [comment]
> Its not easy, simple to reproduce. I use MQTTool and MQTTX. Connect both, disconnect sometimes 1 and then the other.. send messages and repeat that all. Then after some time i see the connection problem if i try to reconnect with MQTTool. I try it all in local network and see not really any issues on debug output. May only here: [D][sMQTTBroker.cpp:96] publish(): topic test Clients 1 [D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
> 
> Err 128? is that a error?

```
14:16:17.285 -> [D][sMQTTBroker.cpp:17] update(): New Client
14:16:17.285 -> [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
14:16:17.285 -> [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool-2061021286
14:16:17.331 -> [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
14:16:41.365 -> [D][sMQTTBroker.cpp:17] update(): New Client
14:16:41.365 -> [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
14:16:41.365 -> [D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_12076250
14:16:41.365 -> [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
14:16:41.428 -> [D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80)
14:16:41.428 -> [D][sMQTTClient.cpp:193] processMessage(): message id:6485
14:16:41.428 -> [D][sMQTTClient.cpp:202] processMessage(): message topic:homie/kitchen-light/cold/#
14:16:41.428 -> [D][sMQTTBroker.cpp:167] findRetainTopic(): findRetainTopic homie/kitchen-light/cold/# 1
14:16:41.428 -> [D][sMQTTBroker.cpp:175] findRetainTopic(): findRetainTopic homie/kitchen-light/cold/value/set qos:1
14:16:41.428 -> [D][sMQTTBroker.cpp:176] findRetainTopic(): findRetainTopic 0
14:16:41.476 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PubAck(0x40)
14:17:16.391 -> [D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
14:17:16.391 -> [D][sMQTTBroker.cpp:38] update(): Clients 1
14:17:41.572 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:17:42.090 -> [D][sMQTTBroker.cpp:17] update(): New Client
14:17:42.090 -> [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
14:17:42.090 -> [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool-2061021286
14:17:42.090 -> [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
14:18:41.573 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:18:42.181 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:18:43.614 -> [D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
14:18:43.660 -> [D][sMQTTBroker.cpp:38] update(): Clients 1
14:19:41.598 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:20:41.592 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:21:41.608 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:22:41.797 -> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
14:23:04.762 -> [D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0)
14:23:04.762 -> [D][sMQTTBroker.cpp:38] update(): Clients 0
```
as you can see from the log, I connected 2 clients, the one that disconnected on the phone due to the fact that it went into sleep mode. After unlocking, he automatically connected to the broker himself. Also, when connecting from a phone, the client took a long time to connect.

**Comment by conaito** [comment]
yes thats the normal scenario but after some time of that tests the problem comes that the client can´t connect again - even 0 clients view in the log. Currently its very bad for me since the connect problem still exist and no other way is possible then reset the esp32. i need any fix if possible. yesterday i complete test over the day and the problem comes 100% after some time.. logs view nothing strange..looks like overload after some time of connect and disconnect and then no new client (on serial views 0 clients connected!) can connect to the broker - i must reset then :(

**Comment by conaito** [comment]
i tested today with latest code but again after a while it happened, this was last debug (may you see here something
?):

[D][sMQTTBroker.cpp:101] publish(): topic test Clients 2
[D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0)
onRemove: MQTTool7863377
[D][sMQTTBroker.cpp:44] update(): Clients 1
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.36 KB
onConnect: MQTTool7863377
[D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0)
onRemove: MQTTool7863377
[D][sMQTTBroker.cpp:44] update(): Clients 1
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.29 KB
onConnect: MQTTool7863377
[D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
onRemove: MQTTool7863377
[D][sMQTTBroker.cpp:44] update(): Clients 1
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.26 KB
onConnect: mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80)
[D][sMQTTClient.cpp:196] processMessage(): message id:52409
[D][sMQTTClient.cpp:205] processMessage(): message topic:test
[D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.20 KB
onConnect: mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80)
[D][sMQTTClient.cpp:196] processMessage(): message id:52411
[D][sMQTTClient.cpp:205] processMessage(): message topic:test
[D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.15 KB
onConnect: mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80)
[D][sMQTTClient.cpp:196] processMessage(): message id:52413
[D][sMQTTClient.cpp:205] processMessage(): message topic:test
[D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)

**Comment by conaito** [comment]
ohh.. this time i was waiting after the problem without reset the esp32 and after a while it was again possible to connect. looks like after update?

[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.09 KB
onConnect: mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80)
[D][sMQTTClient.cpp:196] processMessage(): message id:52415
[D][sMQTTClient.cpp:205] processMessage(): message topic:test
[D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0)
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
252.36 KB
onConnect: mqttx_b5ab42a3_1638368566000
[D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1
onRemove: mqttx_b5ab42a3_1638368566000
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.26 KB
onConnect: MQTTool7863377
[D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0)
onRemove: MQTTool7863377
[D][sMQTTBroker.cpp:44] update(): Clients 0
[D][sMQTTBroker.cpp:17] update(): New Client
[D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10)
[D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377
[D][sMQTTClient.cpp:76] processMessage(): message keepTime:60
254.20 KB
onConnect: MQTTool7863377


may any idea with this info/debug ??

**Comment by conaito** [comment]
looks like it it was only because mqttx was disconnect..

**Comment by conaito** [comment]
i think all in all its the best idea that you provide a version with some more debug info to may faster find the issue. i can made the tests here then and give you all the debug?

**Comment by terrorsl** [comment]
What Arduino core for the ESP32 you use?

**Comment by conaito** [comment]
i use a m5 stack atom. it should be same as pico32
Am 1. Dez. 2021, 19:02 +0100 schrieb terrorsl ***@***.***>:

**Comment by terrorsl** [comment]
> ohh.. this time i was waiting after the problem without reset the esp32 and after a while it was again possible to connect. looks like after update?
> 
> [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.09 KB onConnect: mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80) [D][sMQTTClient.cpp:196] processMessage(): message id:52415 [D][sMQTTClient.cpp:205] processMessage(): message topic:test [D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0 [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 252.36 KB onConnect: mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.26 KB onConnect: MQTTool7863377 [D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0) onRemove: MQTTool7863377 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.20 KB onConnect: MQTTool7863377
> 
> may any idea with this info/debug ?? but shortly problem was coming back now..

client did not send a PingReq within the allotted time and was disconnected.
keepTime 60 second.
i test mqttx always send this message.
as I understand you are connecting to the broker through a router?

**Comment by conaito** [comment]
sure with router. broker run on esp32 and mqttool is on iphone as you know. this you mean?
Am 1. Dez. 2021, 19:09 +0100 schrieb terrorsl ***@***.***>:

**Comment by terrorsl** [comment]
> sure with router. broker run on esp32 and mqttool is on iphone as you know. this you mean? Am 1. Dez. 2021, 19:09 +0100 schrieb terrorsl ***@***.***>:
> […](#)
> > ohh.. this time i was waiting after the problem without reset the esp32 and after a while it was again possible to connect. looks like after update? > [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.09 KB onConnect: mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:42] processMessage(): message type:Subscribe(0x80) [D][sMQTTClient.cpp:196] processMessage(): message id:52415 [D][sMQTTClient.cpp:205] processMessage(): message topic:test [D][sMQTTBroker.cpp:173] findRetainTopic(): findRetainTopic test 0 [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:42] processMessage(): message type:PingReq(0xc0) [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 252.36 KB onConnect: mqttx_b5ab42a3_1638368566000 [D][sMQTTClient.cpp:26] update(): aliveMillis < currentMillis -1 onRemove: mqttx_b5ab42a3_1638368566000 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.26 KB onConnect: MQTTool7863377 [D][sMQTTClient.cpp:42] processMessage(): message type:Disconnect(0xe0) onRemove: MQTTool7863377 [D][sMQTTBroker.cpp:44] update(): Clients 0 [D][sMQTTBroker.cpp:17] update(): New Client [D][sMQTTClient.cpp:42] processMessage(): message type:Connect(0x10) [D][sMQTTClient.cpp:75] processMessage(): message clientId:MQTTool7863377 [D][sMQTTClient.cpp:76] processMessage(): message keepTime:60 254.20 KB onConnect: MQTTool7863377 > may any idea with this info/debug ?? but shortly problem was coming back now.. client did not send a PingReq within the allotted time and was disconnected. keepTime 60 second. i test mqttx always send this message. as I understand you are connecting to the broker through a router? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

OK. You can try to do it without a router to eliminate network problems. That is, switch the board to the access point mode and connect from the phone to it directly or from the computer if there is a Wi-Fi. 
``` c++
// You can remove the password parameter if you want the AP to be open.
  WiFi.softAP(ssid, password);
  IPAddress myIP = WiFi.softAPIP();
  Serial.print("AP IP address: ");
  Serial.println(myIP);
```

**Comment by terrorsl** [comment]
> i use a m5 stack atom. it should be same as pico32 Am 1. Dez. 2021, 19:02 +0100 schrieb terrorsl ***@***.***>:
> […](#)
> What Arduino core for the ESP32 you use? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

as i undestand it is board, i say about framework. in Arduino IDE i use this https://github.com/espressif/arduino-esp32#development-status

**Comment by conaito** [comment]
platfrom expressif32 and framework arduino

![image](https://user-images.githubusercontent.com/77739052/144841949-21d422be-253d-4eca-9ee4-5cab422a00a1.png)

**Comment by folksman** [comment]
may you can implement a property if MaxClients reached and a additional function to restart the server? this may help a bit as workaround..

**Comment by terrorsl** [comment]
For test only?

**Comment by folksman** [comment]
for testing its ik as first if it solve the problem then may implement direct into the lib?
